document.writeln("<header class=\"header\">");
document.writeln("");
document.writeln("    <section class=\"mainWrap\">");
document.writeln("");
document.writeln("        <div class=\"topLine\"></div>");
document.writeln("");
document.writeln("        <section class=\"topWrap\">");
document.writeln("");
document.writeln("         ");
document.writeln("<!-- 网站logo图片地址请在本组件\"内容配置-网站logo\"处填写 -->");
document.writeln("<a href=\"../index.htm\" title=\"新鹏程教育\" class=\"logo\"><img src=\"../images/logo.png\"></a>");
// document.writeln("<a ><img align=\"right\" width=\"120\" src=\"../images/wechart.jpg\"></a>");
document.writeln("");
document.writeln("");
document.writeln("        </section>");
document.writeln("");
document.writeln("        <section class=\"nav yahei  clearfix\">");
document.writeln("");
document.writeln("            <section class=\"menu\" id=\"smenu\"><a class=\"thuicon-menu menuicon\"></a>导航</section>");
document.writeln("");
document.writeln("             <ul id=\"nav\">");
document.writeln("                <li><a href=\"..\\index.htm\">首页</a></li>");
document.writeln("         ");
document.writeln("");
document.writeln("                    <li><a href=\"..\\xlts\\gjkfdx.htm\" title=\"学历提升\">学历提升<i class=\"thuicon-angle-down\"></i></a>");
document.writeln("                            <ul>");
document.writeln("");
document.writeln("                                    <li><a href=\"..\\xlts\\gjkfdx.htm\" title=\"学历提升\">国家开放大学</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                                    <li><a href=\"..\\xlts\\ynzzz.htm\" title=\"一年制中专\">一年制中专</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                                    <li><a href=\"..\\xlts\\wljy.htm\" title=\"网络教育\">网络教育</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                                    <li><a href=\"..\\xlts\\tdxlss.htm\" title=\"同等学历申硕 \">同等学历申硕 </a></li>");
document.writeln("                            </ul>");
document.writeln("                    </li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                <li><a href=\"..\\jnryzyzg\\zyzgz.htm\" title=\"技能人员职业资格\">技能人员职业资格<i class=\"thuicon-angle-down\"></i></a>");
document.writeln("                    <ul>");
document.writeln("");
document.writeln("                        <li><a href=\"..\\jnryzyzg\\zyzgz.htm\" title=\"职业资格证\">职业资格证</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                        <li><a href=\"..\\jnryzyzg\\jkgls.htm\" title=\"健康管理师\">健康管理师</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                        <li><a href=\"..\\jnryzyzg\\ajjrypx.htm\" title=\"安监局人员培训\">安监局人员培训</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("                <li><a href=\"..\\zyjszyzg\\zyjsryzyzg.htm\" title=\"专业技术人员职业资格\">专业技术人员职业资格<i class=\"thuicon-angle-down\"></i></a>");
document.writeln("                    <ul>");
document.writeln("");
document.writeln("                        <li><a href=\"..\\zyjszyzg\\gcs.htm\" title=\"工程师\">工程师</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                        <li><a href=\"..\\zyjszyzg\\jjs.htm\" title=\"经济师\">经济师</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                        <li><a href=\"..\\zyjszyzg\\wlgcs.htm\" title=\"网络工程师\">网络工程师</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                        <li><a href=\"..\\zyjszyzg\\rlzys.htm\" title=\"人力资源师\">人力资源师</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                        <li><a href=\"..\\zyjszyzg\\zqcyzgs.htm\" title=\"证券从业资格师\">证券从业资格师</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                        <li><a href=\"..\\zyjszyzg\\jjcyzgs.htm\" title=\"基金从业资格师\">基金从业资格师</a></li>");
document.writeln("");
document.writeln("");
document.writeln("                        <li><a href=\"..\\zyjszyzg\\kjs.htm\" title=\"会计师\">会计师</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</ul>");
document.writeln("");
document.writeln("        </section>");
document.writeln("");
document.writeln("     </section>");
document.writeln("");
document.writeln("</header>");