document.writeln("<footer class=\"footer\">");
document.writeln("");
document.writeln("        <section class=\"footWrap\">");
document.writeln("");
document.writeln("            <section class=\"mainWrap\">");
document.writeln("");
document.writeln("                <nav class=\"footerNav\">");
document.writeln("");
document.writeln("                    <ul class=\"clearfix\">");
document.writeln("    ");
document.writeln("");
document.writeln("                <li>");
document.writeln("");
document.writeln("                    <h4><a href=\"../xlts/gjkfdx.htm\">学历提升</a></h4>");
document.writeln("");
document.writeln("                            <a href=\"../xlts/gjkfdx.htm\">国家开放大学</a>");
document.writeln("");
document.writeln("                            <a href=\"../xlts/ynzzz.htm\">一年制中专</a>");
document.writeln("");
document.writeln("                            <a href=\"../xlts/wljy.htm\">网络教育</a>");
document.writeln("");
document.writeln("                            <a href=\"../xlts/tdxlss.htm\">同等学历申硕</a>");
document.writeln("                </li>");
document.writeln("");
document.writeln("                <li>");
document.writeln("");
document.writeln("                    <h4><a href=\"../jnryzyzg/zyzgz.htm\">技能职业资格 </a></h4>");
document.writeln("");
document.writeln("                            <a href=\"../jnryzyzg/zyzgz.htm\">职业资格证</a>");
document.writeln("");
document.writeln("                            <a href=\"../jnryzyzg/jkgls.htm\">健康管理师</a>");
document.writeln("");
document.writeln("                            <a href=\"../jnryzyzg/ajjrypx.htm\">安监局人员培训</a>");
document.writeln("                </li>");
document.writeln("");
document.writeln("                <li>");
document.writeln("");
document.writeln("                    <h4><a href=\"../zyjszyzg/gcs.htm\">专业技术职业资格  </a></h4>");
document.writeln("");
document.writeln("                            <a href=\"../zyjszyzg/gcs.htm\">工程师</a>");
document.writeln("");
document.writeln("                            <a href=\"../zyjszyzg/jjs.htm\">经济师</a>");
document.writeln("");
document.writeln("                            <a href=\"../zyjszyzg/wlgcs.htm\">网络工程师</a>");
document.writeln("");
document.writeln("                            <a href=\"../zyjszyzg/rlzy.htm\">人力资源师</a>");
document.writeln("");
document.writeln("                            <a href=\"../zyjszyzg/zqcyzgs.htm\">证券从业资格师</a>");
document.writeln("");
document.writeln("                            <a href=\"../zyjszyzg/jjcyzgs.htm\">基金从业资格师</a>");
document.writeln("");
document.writeln("                            <a href=\"../zyjszyzg/kjs.htm\">会计师</a>");
document.writeln("");
document.writeln("                </li>");
document.writeln("</ul>");
document.writeln("");
document.writeln("                </nav>");
document.writeln("");
document.writeln("            </section>");
document.writeln("");
document.writeln("        </section> <section class=\"copyrights\">");
document.writeln("");
document.writeln("            <section class=\"mainWrap\">");
document.writeln("");
document.writeln("             ");
document.writeln("<section class=\"mainWrap\"> ");
document.writeln(" <span class=\"info\"><span>电话：17106968377</span>");
document.writeln(" <!-- <span>管理员信箱：webmaster@tsinghua.edu.cn</span> -->");
document.writeln(" <span>地址：峰市红山区园林路英华文化大厦4楼</span></span> ");
document.writeln(" <!-- <span class=\"info\"> <a href=\"http://beian.miit.gov.cn\" style=\"color:#a5a2a7;\"><span>京ICP备 15006448 号 </span></a> <span>京公网安备 110402430053 号</span></span>  -->");
document.writeln(" <div class=\"clear\"></div> ");
document.writeln(" <span class=\"copy\">版权所有 © 新鹏程教育</span> ");
document.writeln("</section>");
document.writeln("            </section>");
document.writeln("");
document.writeln("        </section>");
document.writeln("");
document.writeln("</footer>");