document.writeln("<head>");
document.writeln("");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">");
document.writeln("");
document.writeln("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />");
document.writeln("");
document.writeln("<title>新鹏程教育</title><META Name=\"keywords\" Content=\"新鹏程教育,学历提升,技能人员职业资格,专业技术人员职业资格\" />");
document.writeln("");
document.writeln("");
document.writeln("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"../images/favicon.ico\" /> ");
document.writeln("");
document.writeln("<link href=\"../newthu/newthu_cnt/css/base.css\" rel=\"stylesheet\" type=\"text/css\">");
document.writeln("");
document.writeln("<link href=\"../newthu/newthu_cnt/css/inner.css\" rel=\"stylesheet\" type=\"text/css\">");
document.writeln("");
document.writeln("<link rel=\"stylesheet\" href=\"../newthu/newthu_cnt/font/css/thuicon.css\">");
document.writeln("");
document.writeln("<script src=\"../newthu/newthu_cnt/js/jq.js\" type=\"text/javascript\"></script>");
document.writeln("");
document.writeln("<script src=\"../newthu/newthu_cnt/js/comm.js\" type=\"text/javascript\"></script>");
document.writeln("");
document.writeln("<!--[if lt IE 9]>");
document.writeln("");
document.writeln("<script src=\"../newthu/newthu_cnt/js/html5.js\" type=\"text/javascript\"></script>");
document.writeln("");
document.writeln("<![endif]-->");
document.writeln("");
document.writeln("<!--[if IE 7]>");
document.writeln("");
document.writeln("<link rel=\"stylesheet\" href=\"../newthu/newthu_cnt/font/css/thuicon-ie7.css\">");
document.writeln("");
document.writeln("<![endif]-->");
document.writeln("");
document.writeln("<!--Announced by Visual SiteBuilder 9-->");
document.writeln("<link rel=\"stylesheet\" type=\"text/css\" href=\"../_sitegray/_sitegray_d.css\" />");
document.writeln("<script language=\"javascript\" src=\"../_sitegray/_sitegray.js\"></script>");
document.writeln("<!-- CustomerNO:77656262657232300201465c -->");
document.writeln("<link rel=\"stylesheet\" type=\"text/css\" href=\"../xxyg-jjy.vsb.css\" />");
document.writeln("<script type=\"text/javascript\" src=\"../system/resource/js/counter.js\"></script>");
document.writeln("<script type=\"text/javascript\">_jsq_(1004,\'/xxyg-jjy.jsp\',-1,1623241808)</script>");
document.writeln("</head>");